name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_and_test:
    name: Test Core
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialise Submodule
        run: git submodule init && git submodule update
      - name: Test
        working-directory: ./Core
        run: swift test
