name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialise Submodule
        run: git submodule init && git submodule update
      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
      - name: Build
        run: xcodebuild build-for-testing -scheme "FeedRadar" -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" | xcbeautify
      - name: Test
        run: xcodebuild test-without-building -scheme "FeedRadar" -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" | xcbeautify